# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('recv_name', models.CharField(max_length=255)),
                ('recv_address', models.CharField(max_length=255)),
                ('recv_phone', models.CharField(max_length=255)),
                ('recv_remark', models.CharField(max_length=255)),
                ('totable', models.FloatField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oi_goods_id', models.CharField(max_length=255)),
                ('oi_goods_name', models.CharField(max_length=255)),
                ('oi_goods_price', models.FloatField()),
                ('oi_goods_count', models.IntegerField()),
                ('deal_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
