# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('userpass', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('header', models.ImageField(default='static/images/headers/默认头像.png', upload_to='static/images/headers')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('regist_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 16, 6, 17, 192795))),
            ],
        ),
    ]
