# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190304_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.CharField(default='/static/myblog/git.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(max_length=16, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
