# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190305_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater1',
            field=models.ImageField(default='/static/myblog/git.png', upload_to='static/img/'),
        ),
    ]
